### ISSUE TITLE
Unable to get window to connect to mutscratch

### ISSUE THREAD

**Issue by webbb82** [jrwrigh/qtile-mutable-scratch#2]
I could be doing this wrong but I followed the readme, onlything is  i cant tell if i am just overthinking this or what but I cant figure out if im suppose to type in the terminal like in the video or what. I tried the keybinds nothing. I added the code to my config.py and just nothing.  Also when i do qtile check it says
```
qtile check
Checking Qtile config at: /home/llama/.config/qtile/config.py
error: config failed to import, NameError: name 'MutableScratch' is not defined
Stub: in file /tmp/tmpuop8vmzc/config.pyi:1
MypyFile:1(
  /tmp/tmpuop8vmzc/config.pyi)
Runtime:
MISSING
```

**Comment by jrwrigh** [comment]
So you need to install the package. I see that I didn't actually include that in the README. I guess I was hoping to get it onto PyPI and have it be installed that way... But time and business.

Looks like Python can't find  the `src/MutableScratch.py` file. Where did you put it in relationship to your `config.py`?

**Comment by jrwrigh** [comment]
The simplest way to get it to work is to place the `MutableScratch.py` file in the same directory as your `config.py` file. Then python should be able to import the module fine.

**Comment by webbb82** [comment]
yea so i just winged it and put that in the main qtile folder. was thinking about putting jt in the scripts folder but . so what would be the best way of goong about installing it?
  

  

  

  
  
  
  
  
>

**Comment by jrwrigh** [comment]
I'm assuming by "main qtile folder" you mean `~/.config/qtile`, and you probably have your config in `~/.config/qtile/config.py`. If that's the case, it looks like you probably already have it where it should work....

**Comment by webbb82** [comment]
ya sorry i should have said that better but you understood. ill jabe to double check that i did that when i get home and try.. so   
  
if thays good how do i go about     
  

  
triggering a window swallow. just the keybind ? or do i type in the terminal like in the video? if you want I'm sure you are busy. once I wrap my head around all this I can write up a simple layman's guide on how it works.    I think you have something great here.   
  

  
  
  
  
  
>

**Comment by jrwrigh** [comment]
> if thays good how do i go about triggering a window swallow. just the keybind ? or do i type in the terminal like in the video?

Yep, everything is just controlled through keybindings (though I'm sure you could call the functions through `qtile shell` or something similar). The terminal typing was only to uniquely mark the windows, such that it was possible to see that I was cycling through multiple windows. And also to communicate what exactly I was hoping to show in the video.

> once I wrap my head around all this I can write up a simple layman's guide on how it works.    I think you have something great here.

Sure, that'd be great. Always good to have another opinion on how to explain it. The video is hard to do since the scratch windows disappear from screen.

**Comment by webbb82** [comment]
I knew your name looked familiar. I keep seeing it in my email we are in many of the same groups. While,    bronite, helix and think one more   
  

  

  
  
  
  
  
>

**Comment by jrwrigh** [comment]
I don't think so. I don't use helix and haven't heard of bronite before.

**Comment by webbb82** [comment]
Well that is odd. I suppose there can be two James Wright's into Linux.   
  
  

    
  

  
  
  
  
  
>

**Comment by webbb82** [comment]
alright, just got home and put the SC/Mutablescratch file in the root of ,config/qtile. Doing so had zero effect. My next step was to put the file out of the "SC" folder.  Still nothing changed . I then tried putting both in the Qtile/scripts folder, and..... nothing, 
I figured maybe its the permissions. I checked, and that file is RWRR I think that is good. and when I run Qtile check I still get the exact same error.

```
llama  ~  ♥ 16:57  qtile check
Checking Qtile config at: /home/llama/.config/qtile/config.py
error: config failed to import, NameError: name 'MutableScratch' is not defined
Stub: in file /tmp/tmppfxt9_uq/config.pyi:1
MypyFile:1(
```

I looked around the googles and saw that this error means python didn't see mutablescratch being used in any meaningful way. Im not sure what to make of that in this case.

**Comment by jrwrigh** [comment]
Can you post your `config.py` file?

**Comment by webbb82** [comment]
for sure here it is https://pastebin.com/cCQE12C2. its not pretty so be kind lol

**Comment by jrwrigh** [comment]
Gotcha. You need to import the module first. So something like:
```python
# Setup MutableScratch
from MutableScratch import MutableScratch
mutscr = MutableScratch()
groups.append(Group(''))
 
keys.extend( [
   EzKey('M-S-<minus>', mutscr.add_current_window()),
   EzKey('M-<minus>',   mutscr.toggle()),
   EzKey('M-C-<minus>', mutscr.remove()),
] )
 
hook.subscribe.startup_complete(mutscr.qtile_startup)
```

Also note the last line. I had a typo in the README (so trade out `minscr` -> `mutscr`)

**Comment by jrwrigh** [comment]
I'm about to have the package uploaded to PyPI real quick, so you can actually test out installing it "normally" and see how that works.

**Comment by webbb82** [comment]
ya know I had something like that but after deleting reading changing so much I must have forgot that code. Isnt that the code on the github page?

**Comment by webbb82** [comment]
yea I have that on line 92 i think in my config

**Comment by jrwrigh** [comment]
You're missing the first line:
```python
from MutableScratch import MutableScratch
```

**Comment by webbb82** [comment]
ahhhhhhh yes yes, I see

**Comment by webbb82** [comment]
well the error about your stuff is gone , now its back to the old error ive been fighting 

llama  ~  ♥ 19:21  qtile check
Checking Qtile config at: /home/llama/.config/qtile/config.py
error: config failed to import, NameError: name 'groups' is not defined

How are they goig to say groups is not defined that word is used so much, and I have zero clue how to fix that

**Comment by jrwrigh** [comment]
Because `groups` isn't defined yet. It only gets defined on line 126, so the MutableScratch setup needs to happen *at least* after that.

**Comment by webbb82** [comment]
ok ill give that a shot, I really appreciate your assistance, after staring at this code so long you start to miss things

**Comment by jrwrigh** [comment]
Also, the package is up on PyPI now: https://pypi.org/project/qtile-mutable-scratch/0.0.1/

So you could try installing it through that. That'll actually be the preferred method from here on out. I've pushed up updates to the `README` now to reflect the change in installation (as well as some change in function names. Mainly for consistency).

**Comment by webbb82** [comment]
Ill do that I moved your code to the bottom and now its telling me error: config failed to import, NameError: name 'EzKey' is not defined

**Comment by jrwrigh** [comment]
I am really not helping you out with my incomplete documentation. :cold_sweat: 

You need to add:
```python
from libqtile.config import EzKey
```

Also, make sure you have `libqtile.hook` imported as well. Looks like you do.

**Comment by jrwrigh** [comment]
README has been updated to include those now as well.

**Comment by webbb82** [comment]
Na your good I think im just not patient . you are doing an awesome job,

**Comment by webbb82** [comment]
ok gotta love software dev lol

/tmp/tmp7rhiwlns/config.py:4: error: Skipping analyzing "qtile_mutable_scratch": module is 
installed, but missing library stubs or py.typed marker  [import]

this is my import section
import os
import re
import socket
import subprocess, qtile_mutable_scratch
from typing import List  # noqa: F401
from libqtile import layout, bar, widget, hook, qtile
from libqtile.config import Click, Drag, Group, Key, Match, Screen, Rule, DropDown, ScratchPad,KeyChord, EzKey
from libqtile.command import lazy
from libqtile.widget import Spacer

**Comment by webbb82** [comment]
it also printed this link https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports

**Comment by jrwrigh** [comment]
Is that an actual error or a message from `mypy`? ie. does the qtile log actually say that it's not going to proceed.

Also, what version of qtile are you using? I didn't know that qtile was calling `mypy` to check it's config before loading.

**Comment by jrwrigh** [comment]
From that mypy documentation link:
> If you get any of these errors on an import, mypy will assume the type of that module is Any, the dynamic type.

That reads to me like it's just complaining, but qtile has (or should) read the config just fine.

**Comment by jrwrigh** [comment]
Looks like you can do:
```python
import qtile_mutable_scratch # type: ignore
```

to get it to not report an error.

**Comment by webbb82** [comment]
ya it should run I just wanted to repot that incase it was useful in anyway to ya, again appreciate the help. SO now to get it to swallow a window  I press Super + M? or do like in the video?

**Comment by jrwrigh** [comment]
So for `EzKey`, the `M` is the super key. So
`EzKey('M-S-<minus>', mutscr.add_current_window()),` is Super + Shift + `-`, which will add (swallow) the window.

**Comment by webbb82** [comment]
ah gotcha  so this should work also if I want to change the keys?
    EzKey([mod3], "space", mutscr.add_current_window()),

**Comment by jrwrigh** [comment]
If you want to use `[mod3]` similar to the rest of your config, you have to use `Key`.

So `EzKey('M-S-<space>', mutscr.add_current_window())` is equivalent to `Key(['super', 'shift'], 'space', mutscr.add_current_window())`.

**Comment by webbb82** [comment]
gotcha, well man again I really want to say thank you for your assistance. This has been a long back and forth. Like I said ill collect all this info and give you a white up if you want to add it to the page  you can if not thats fine also.  Just my way of saying thanks

**Comment by jrwrigh** [comment]
Welcome! Let me know if you have any questions.

Also, as far as documenting, just submit a PR of what changes you think should be made to the README.

**Comment by webbb82** [comment]
Ya for sure. Honestly they are fine now with the added data but I just wanted to help us out. It's not that they are lacking still   
  

  

  

  
  
  
  
  
>
